use penguin::*;

fn parse_source(source: &str) -> PengAST {
    let tokens = lex_source(source.to_string()).expect("source should lex");
    parse(tokens).expect("source should parse")
}

fn script_statements(ast: &PengAST) -> &Vec<PengPositionedStatement> {
    match ast {
        PengAST::Script(statements) => statements,
        PengAST::Program(_) => panic!("expected script"),
    }
}

fn expression_statement(statement: &PengPositionedStatement) -> &PengPositionedExpression {
    match &statement.value {
        PengStatement::Expression(expression) => expression,
        _ => panic!("expected expression statement"),
    }
}

fn generated_bytecode(source: &str, globals: &[&str]) -> Vec<PengInstruction> {
    let ast = parse_source(source);
    let mut env = PengEnv::new();

    for global in globals {
        env.create_global((*global).to_string());
    }

    let function_ptr = generate_script(&mut env, &ast).expect("script should generate");
    match env.get_value(function_ptr) {
        Some(PengValue::Function(PengFunction::Bytecode(function))) => {
            function.bytecode.clone()
        }
        _ => panic!("expected generated bytecode function"),
    }
}

#[test]
fn parses_short_circuit_and_strict_logical_operators_separately() {
    let ast = parse_source("true | false || true & false && true");
    let expression = expression_statement(&script_statements(&ast)[0]);

    let outer = match &expression.value {
        PengExpression::Binary {
            operator: PengBinaryOperator::ShortCircuitOr,
            right,
            ..
        } => right,
        _ => panic!("expected short-circuit or"),
    };

    match &outer.value {
        PengExpression::Binary {
            operator: PengBinaryOperator::ShortCircuitAnd,
            left,
            ..
        } => match &left.value {
            PengExpression::Binary {
                operator: PengBinaryOperator::NonShortCircuitAnd,
                ..
            } => {}
            _ => panic!("expected strict and"),
        },
        _ => panic!("expected short-circuit and"),
    }
}

#[test]
fn pipe_builds_a_union_only_after_union_keyword() {
    let ast = parse_source(
        "var a = union int|uint\n\
         union u = int|uint\n\
         var b = int|uint",
    );
    let statements = script_statements(&ast);

    for index in [0usize, 1usize] {
        let declaration = match &statements[index].value {
            PengStatement::Declaration(PengDeclaration::Variable(variable)) => {
                match &variable.value.value {
                    Some(PengPositioned {
                        value: PengExpression::Type(value),
                        ..
                    }) => value,
                    _ => panic!("expected union value"),
                }
            }
            PengStatement::Declaration(PengDeclaration::Type(declaration)) => {
                declaration.value.value.as_ref().expect("union type value")
            }
            _ => panic!("expected declaration"),
        };

        assert!(matches!(
            declaration.value,
            PengTypeExpression::Union(_)
        ));
    }

    let value = match &statements[2].value {
        PengStatement::Declaration(PengDeclaration::Variable(variable)) => {
            variable.value.value.as_ref().expect("variable value")
        }
        _ => panic!("expected variable declaration"),
    };
    assert!(matches!(
        value.value,
        PengExpression::Binary {
            operator: PengBinaryOperator::NonShortCircuitOr,
            ..
        }
    ));

    let nested = parse_source("var values = union [int|uint]");
    let nested_value = match &script_statements(&nested)[0].value {
        PengStatement::Declaration(PengDeclaration::Variable(variable)) => {
            variable.value.value.as_ref().expect("variable value")
        }
        _ => panic!("expected variable declaration"),
    };
    match &nested_value.value {
        PengExpression::Type(PengPositioned {
            value: PengTypeExpression::Vector(inner),
            ..
        }) => assert!(matches!(inner.value, PengTypeExpression::Union(_))),
        _ => panic!("expected vector with union inner type"),
    }
}

#[test]
fn parses_try_else_chains_and_try_as_an_infix_operation() {
    let ast = parse_source(
        "try f() else try g()\n\
         var x = try f(2) else try g() else try h()\n\
         10 try getoper(10,30) 20",
    );
    let statements = script_statements(&ast);

    assert!(matches!(
        expression_statement(&statements[0]).value,
        PengExpression::Try { .. }
    ));

    let variable_value = match &statements[1].value {
        PengStatement::Declaration(PengDeclaration::Variable(variable)) => {
            variable.value.value.as_ref().expect("variable value")
        }
        _ => panic!("expected variable declaration"),
    };
    assert!(matches!(variable_value.value, PengExpression::Try { .. }));

    match &expression_statement(&statements[2]).value {
        PengExpression::OperationCall { operation, .. } => {
            assert!(matches!(operation.value, PengExpression::Try { .. }));
        }
        _ => panic!("expected operation call"),
    }
}

#[test]
fn generates_short_circuit_jumps_but_keeps_pipe_and_ampersand_strict() {
    let bytecode = generated_bytecode(
        "true && false\ntrue || false\ntrue & false\ntrue | false",
        &[],
    );

    assert!(bytecode.iter().any(|instruction| {
        matches!(instruction, PengInstruction::JumpIfFalse(_))
    }));
    assert!(bytecode.iter().any(|instruction| {
        matches!(instruction, PengInstruction::JumpIfTrue(_))
    }));
    assert!(bytecode.iter().any(|instruction| {
        matches!(instruction, PengInstruction::And)
    }));
    assert!(bytecode.iter().any(|instruction| {
        matches!(instruction, PengInstruction::Or)
    }));
}

#[test]
fn catches_try_expressions_and_leaves_unhandled_statement_errors_to_runtime() {
    let expression_bytecode = generated_bytecode("var a = try f()", &["f"]);
    assert!(expression_bytecode.iter().any(|instruction| {
        matches!(instruction, PengInstruction::TryFunctionCall { .. })
    }));

    let statement_bytecode = generated_bytecode("try f() else try g()", &["f", "g"]);
    assert_eq!(
        statement_bytecode
            .iter()
            .filter(|instruction| {
                matches!(instruction, PengInstruction::TryFunctionCall { .. })
            })
            .count(),
        1
    );
    assert_eq!(
        statement_bytecode
            .iter()
            .filter(|instruction| {
                matches!(instruction, PengInstruction::FunctionCall { .. })
            })
            .count(),
        1
    );
}
